name : 'StorageSystem'
version: '2.0.2'
api-version: '1.21'
main: com.emeraldingot.storagesystem.StorageSystem
commands:
  storagesystem:
    description: "StorageSystem command"
    usage: /<command> <argument>
permissions:
  storagesystem.admin:
    description: "Allows use of admin tools and commands"
    default: op
  storagesystem.use:
    description: "Allows use of the storage system by players"
    default: true