name : 'StorageSystem'
version: '1.0.0'
api-version: '1.21.7'
main: com.emeraldingot.storagesystem.StorageSystem
commands:
  storagesystem:
    description: "StorageSystem command"
    usage: /<command> <argument>